version: '3'
services:
  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - 5000:5000
    environment:
      LT_LOAD_ONLY: en,de
  backend:
    build: ./backend
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - TRANSLATE_API_URL=http://localhost:5000
  frontend:
    build: ./frontend
    ports:
      - 8100:8100
    depends_on:
      - backend